#!/bin/bash

## Determine OS, if apt is present it's Debian-based, if not, then it's Red Hat-based.
ARCH=$(uname -m)
echo $ARCH
if [[ `apt-get 2>&1` =~ command\ not ]]
then
    OS=redhat
fi
if [[ ${OS} = "redhat" && ${ARCH} = "i686" ]]
then
echo "UnSupported OS"

elif [[ ${OS} = "redhat" && ${ARCH} = "x86_64" ]]
then

rpm -e pivotal-redis.x86_64

else
apt-get purge -y pivotal-redis
fi

