#!/bin/bash

# Verify if redis is running
pid=$(ps aux |grep  pivotal-redis |grep -v grep | awk '{print $2}')
echo $pid
        if [ -n "$pid" ]; then
                echo "process is running ... hence continuing..."
        else
                 echo "Process is not there... Hence exiting..."
                 exit
        fi

# Command line Redis
        cd /opt/pivotal/pivotal-redis/util
        echo "The present working directory"
        pwd


# create a second instance for replication
        ./redis-instance.sh -p 9011


#Edit conf file for replication

#line="slaveof <masterip> <masterport>"
#sed -i "/${line}/ s/# *//" redis-9011.conf
#sed -i 's/<masterip>/localhost/g' redis-9011.conf
#sed -i 's/<masterport>/6379/g' redis-9011.conf
sed -i "s/# slaveof <masterip> <masterport>/slaveof vmc-ssrc-rh28 6379\n# slaveof <masterip> <masterport>/" /etc/opt/pivotal/pivotal-redis/redis-9011.con

# Start redis 9011 server
	service pivotal-redis-9011 start
	service pivotal-redis-9011 status

su -l p-redis  << EOF
    whoami
    cd /opt/pivotal/pivotal-redis/bin
    ./redis-cli
    
    PING
    set mykey "Test Replication"
    get mykey
    exit
EOF

su -l p-redis  << EOF
    whoami
    cd /opt/pivotal/pivotal-redis/bin
    ./redis-cli -p 9011

    PING
    set mykey "Test Replication"
    get mykey
    exit
EOF
